version: "2"

networks:
  global:
    external:
      name: global-network

services:

  # Database
  pictureweb-mongo:
    image: mongo
    ports:
     - "27017:27017"
    restart: always
    env_file: 
     - pictureweb-environment
    volumes:
     - "${CONTAINERDATA}/pictureweb/db:/data/db"
  pictureweb-datastore:
    image: tvvk/pictureweb-datastore
    links:
     - "pictureweb-mongo"
    restart: always
    env_file:
     - "pictureweb-environment"
    ports:
     - "localhost:8081:8081"
     
  # Web
  pictureweb-web:
    image: tvvk/pictureweb-web
    networks:
     - "global"
     - "default"
    links:
     - "pictureweb-datastore"    
    ports:
     - "8080:8080"
    restart: always
    env_file:
     - "pictureweb-environment"
    volumes:
     - "${CONTAINERDATA}/pictureweb/images:/data/storage"


  # Services
  pictureweb-flickr-fetcher:
    image: tvvk/pictureweb-flickr-fetcher
    links:
     - "pictureweb-datastore"    
    restart: always
    env_file:
     - "pictureweb-environment"
    volumes:
     - "${CONTAINERDATA}/pictureweb/images:/data/storage"
