version: "2"

networks:
  global:
    external:
      name: global-network

services:

  # Database
  pictureweb-mongo:
    image: mongo
    ports:
     - "27017:27017"
    restart: always
    env_file: 
     - pictureweb-environment
     
  # Web
  pictureweb-web:
    image: tvvk/pictureweb-web
    networks:
     - "global"
     - "default"
    links:
     - "pictureweb-mongo"    
    ports:
     - "8081:8080"
    restart: always
    env_file:
     - "pictureweb-environment"

  # Services
  pictureweb-flickr-fetcher:
    image: tvvk/pictureweb-flickr-fetcher
    links:
     - "pictureweb-mongo"    
    restart: always
    env_file:
     - "pictureweb-environment"
  pictureweb-flickr-downloader:
    image: tvvk/pictureweb-flickr-downloader
    links:
     - "pictureweb-mongo"    
    restart: always
    env_file:
     - "pictureweb-environment"

