#!/bin/bash

export SW_CONTAINERDATA=/home/thomas/container_data/

for dir in `find -name 'docker-compose.yml' -printf '%h\n'`
do
  cd $dir
  echo "Running docker-compose in $(pwd)"
  docker-compose pull
  docker-compose up -d
  cd -
done

echo "Finished"

