version: "2"

networks:
  global:
    external:
      name: global-network

services:

  # Web
  tfmaps:
    image: tvvk/tfmaps
    networks:
     - "global"
     - "default"
    restart: always
    environment:
     - googleMapsApiKey=${TFMAPS_GOOGLEMAPSAPIKEY}
