version: "2"

networks:
  global:
    external:
      name: global-network

services:

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    expose:
     - "8080"
    restart: always
    volumes:
     - "${CONTAINERDATA}/jenkins:/var/jenkins_home"
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - global
