version: "2"
services:

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    ports:
     - "8082:8080"
     - "50000:50000"
    volumes:
     - "${SW_CONTAINERDATA}/jenkins:/var/jenkins_home"
     - /var/run/docker.sock:/var/run/docker.sock
    restart: always

