version: "2"

networks:
  global:
    external:
      name: global-network

services:

  # Infrastructure
  nginx:
    image: library/nginx
    ports:
     - "80:80"
     - "443:443"
    external_links:
     - "jenkins"
     - "pictureweb-web"
     - "pictureweb-eureka"
    networks:
     - "global"
    restart: always
    volumes:
     - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
     - "./nginx/sites/:/etc/nginx/sites-enabled/:ro"
     - "/etc/letsencrypt/:/letsencrypt/:ro"
     - "${CONTAINERDATA}/nginx/:/data/:rw"
